# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtddo_NijJH-p0IAmSXy9GVaXso3fRM3
"""

import sqlite3
import pandas as pd
import os

#Database Setup
def connect_db():
    db_file = 'library.db'
    max_retries = 2
    for attempt in range(max_retries):
        try:
            conn = sqlite3.connect(db_file)
            cursor = conn.cursor()
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS books (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    author TEXT NOT NULL,
                    year INTEGER NOT NULL
                )
            ''')
            conn.commit()
            return conn
        except sqlite3.DatabaseError as e:
            if attempt < max_retries - 1:
                print(f"Database error detected on attempt {attempt + 1}: {e}. Removing malformed database and retrying...")
                if os.path.exists(db_file):
                    os.remove(db_file)
                if 'conn' in locals() and conn:
                    conn.close()
            else:
                print(f"Failed to connect and initialize database after {max_retries} attempts.")
                raise
    return None

conn = connect_db()
#Core Operations
def add_book(title, author, year):
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO books (title, author, year) VALUES (?, ?, ?)",
        (title, author, year)
    )
    conn.commit()

def view_books():
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM books")
    return cursor.fetchall()

def search_book_by_title(title):
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM books WHERE title LIKE ?",
        ('%' + title + '%',)
    )
    return cursor.fetchall()

def update_book(book_id, title=None, author=None, year=None):
    cursor = conn.cursor()
    if title:
        cursor.execute("UPDATE books SET title = ? WHERE id = ?", (title, book_id))
    if author:
        cursor.execute("UPDATE books SET author = ? WHERE id = ?", (author, book_id))
    if year is not None:
        cursor.execute("UPDATE books SET year = ? WHERE id = ?", (year, book_id))
    conn.commit()

def delete_book(book_id):
    cursor = conn.cursor()
    cursor.execute("DELETE FROM books WHERE id = ?", (book_id,))
    conn.commit()

#Load books from CSV dataset
def preload_books_from_csv():
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM books")
    count = cursor.fetchone()[0]

    if count == 0:
        if not os.path.exists('books.csv'):
            print("books.csv file not found in this folder. Please add it and rerun.")
            return

        df = pd.read_csv('books.csv', sep=None, engine='python', on_bad_lines='warn')
        required_cols = {'Title', 'Author', 'Year'}
        if not required_cols.issubset(df.columns):
            print("books.csv must have columns: Title, Author, Year")
            return

        for _, row in df.iterrows():
            title = str(row['Title'])
            author = str(row['Author'])
            try:
                year = int(row['Year'])
            except ValueError:
                print(f"Skipping row with invalid year: {row}")
                continue
            add_book(title, author, int(year))

        print("Books loaded from books.csv into database.")

#User Interface
def main_menu():
    print("--- Library Management System ---")
    print("1. Add Book")
    print("2. View All Books")
    print("3. Search Book by Title")
    print("4. Update Book")
    print("5. Delete Book")
    print("6. Exit")

def main():
    preload_books_from_csv()  # load dataset once if DB empty

    while True:
        main_menu()
        choice = input("Enter choice (1-6): ").strip()

        if choice == '1':
            title = input("Book title: ").strip()
            author = input("Author: ").strip()
            year = input("Year: ").strip()
            if not (title and author and year.isdigit()):
                print("Invalid input. Please enter again.")
                continue
            add_book(title, author, int(year))
            print("Book added successfully.")

        elif choice == '2':
            books = view_books()
            if not books:
                print("No books in database.")
            else:
                print("ID | Title | Author | Year")
                print("-" * 60)
                for b in books:
                    print(f"{b[0]} | {b[1]} | {b[2]} | {b[3]}")

        elif choice == '3':
            keyword = input("Enter title keyword: ").strip()
            results = search_book_by_title(keyword)
            if not results:
                print("No matching books found.")
            else:
                print("Search Results:")
                print("ID | Title | Author | Year")
                print("-" * 60)
                for b in results:
                    print(f"{b[0]} | {b[1]} | {b[2]} | {b[3]}")

        elif choice == '4':
            book_id = input("Enter Book ID to update: ").strip()
            if not book_id.isdigit():
                print("Invalid Book ID.")
                continue
            title = input("New title (leave blank to keep same): ").strip()
            author = input("New author (leave blank to keep same): ").strip()
            year_in = input("New year (leave blank to keep same): ").strip()
            year = int(year_in) if year_in.isdigit() else None
            update_book(int(book_id), title or None, author or None, year)
            print("Book updated (if ID existed).")

        elif choice == '5':
            book_id = input("Enter Book ID to delete: ").strip()
            if not book_id.isdigit():
                print("Invalid Book ID.")
                continue
            delete_book(int(book_id))
            print("Book deleted (if ID existed).")

        elif choice == '6':
            print("Exiting. Goodbye!")
            conn.close()
            break

        else:
            print("Invalid choice. Please enter a number 1–6.")

main()

#library_management_system()